import type { PlatformConfig, Platform } from '../types';

export const PLATFORM_CONFIGS: Record<Platform, PlatformConfig> = {
  web: {
    id: 'web',
    label: 'Web App',
    icon: '🌐',
    color: '#4db8ff',
    description: 'React, Vue, Svelte, Next.js — any modern web framework',
    frameworks: ['React + Vite', 'Next.js', 'Vue 3', 'Svelte', 'Nuxt', 'Remix', 'Astro'],
    deployTargets: ['vercel', 'netlify', 'firebase'],
    canPreview: true,
    previewType: 'iframe',
  },
  ios: {
    id: 'ios',
    label: 'iOS App',
    icon: '🍎',
    color: '#a0a0a0',
    description: 'React Native + Expo — native iOS apps with JS/TS',
    frameworks: ['React Native + Expo', 'React Native CLI', 'Capacitor'],
    deployTargets: ['appstore'],
    canPreview: true,
    previewType: 'device',
  },
  android: {
    id: 'android',
    label: 'Android App',
    icon: '🤖',
    color: '#3ddc97',
    description: 'React Native + Expo — native Android with JS/TS',
    frameworks: ['React Native + Expo', 'React Native CLI', 'Capacitor'],
    deployTargets: ['playstore'],
    canPreview: true,
    previewType: 'device',
  },
  desktop: {
    id: 'desktop',
    label: 'Desktop App',
    icon: '🖥️',
    color: '#ffc857',
    description: 'Electron or Tauri — cross-platform desktop apps',
    frameworks: ['Electron + React', 'Tauri + React', 'Electron + Vue'],
    deployTargets: ['electron'],
    canPreview: false,
    previewType: 'terminal',
  },
  extension: {
    id: 'extension',
    label: 'Browser Extension',
    icon: '🧩',
    color: '#f178b6',
    description: 'Chrome, Firefox, Edge extensions using Manifest V3',
    frameworks: ['Chrome Extension MV3', 'Firefox Extension', 'WXT Framework'],
    deployTargets: ['chrome-store'],
    canPreview: false,
    previewType: 'terminal',
  },
  api: {
    id: 'api',
    label: 'API / Backend',
    icon: '⚙️',
    color: '#ff8c5a',
    description: 'REST or GraphQL API — Node, Python, Go, or Rust',
    frameworks: ['Node.js + Express', 'FastAPI (Python)', 'Go + Gin', 'Hono', 'NestJS'],
    deployTargets: ['railway', 'fly', 'vercel'],
    canPreview: false,
    previewType: 'terminal',
  },
  fullstack: {
    id: 'fullstack',
    label: 'Full-Stack',
    icon: '⚡',
    color: '#7c6af7',
    description: 'Web + API + DB — complete production-ready application',
    frameworks: ['Next.js + Prisma', 'Remix + Prisma', 'SvelteKit', 'Nuxt + Nitro'],
    deployTargets: ['vercel', 'railway', 'fly'],
    canPreview: true,
    previewType: 'iframe',
  },
};

export const PLATFORM_COMBOS = [
  {
    id: 'web-app',
    label: 'Web App',
    platforms: ['web'] as Platform[],
    icon: '🌐',
    popular: true,
  },
  {
    id: 'mobile-app',
    label: 'Mobile App',
    platforms: ['ios', 'android'] as Platform[],
    icon: '📱',
    popular: true,
  },
  {
    id: 'fullstack',
    label: 'Full-Stack',
    platforms: ['fullstack'] as Platform[],
    icon: '⚡',
    popular: true,
  },
  {
    id: 'universal',
    label: 'Universal (Web + Mobile)',
    platforms: ['web', 'ios', 'android'] as Platform[],
    icon: '🌍',
    popular: false,
  },
  {
    id: 'desktop-app',
    label: 'Desktop App',
    platforms: ['desktop'] as Platform[],
    icon: '🖥️',
    popular: false,
  },
  {
    id: 'browser-extension',
    label: 'Browser Extension',
    platforms: ['extension'] as Platform[],
    icon: '🧩',
    popular: false,
  },
  {
    id: 'api-backend',
    label: 'API / Backend',
    platforms: ['api'] as Platform[],
    icon: '⚙️',
    popular: false,
  },
  {
    id: 'everything',
    label: 'Everything',
    platforms: ['web', 'ios', 'android', 'desktop', 'extension', 'api'] as Platform[],
    icon: '🚀',
    popular: false,
  },
];

export const AI_MODELS = [
  {
    id: 'claude-sonnet-4-6',
    name: 'Claude Sonnet 4.6',
    provider: 'anthropic' as const,
    contextWindow: 200000,
    capabilities: ['code', 'reasoning', 'vision', 'tools'],
    maxOutput: 64000,
  },
  {
    id: 'claude-opus-4-6',
    name: 'Claude Opus 4.6',
    provider: 'anthropic' as const,
    contextWindow: 200000,
    capabilities: ['code', 'reasoning', 'vision', 'tools', 'deep-thinking'],
    maxOutput: 32000,
  },
  {
    id: 'claude-haiku-4-5-20251001',
    name: 'Claude Haiku 4.5',
    provider: 'anthropic' as const,
    contextWindow: 200000,
    capabilities: ['code', 'fast'],
    maxOutput: 32000,
  },
];

export const getLanguageFromFilename = (filename: string): string => {
  const ext = filename.split('.').pop()?.toLowerCase() ?? '';
  const map: Record<string, string> = {
    ts: 'typescript',
    tsx: 'typescriptreact',
    js: 'javascript',
    jsx: 'javascriptreact',
    json: 'json',
    css: 'css',
    html: 'html',
    py: 'python',
    go: 'go',
    rs: 'rust',
    md: 'markdown',
    sh: 'shell',
    yaml: 'yaml',
    yml: 'yaml',
    toml: 'toml',
    env: 'plaintext',
    prisma: 'prisma',
    graphql: 'graphql',
    gql: 'graphql',
    sql: 'sql',
    swift: 'swift',
    kt: 'kotlin',
  };
  return map[ext] ?? 'plaintext';
};
